# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
url: "https://www.stephaniejhamilton.com" # the base hostname & protocol for your site
imageurl: "" #"https://unsplash.it/2600/500?random"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Stephanie Hamilton
  #avatar: avatar.png
  hometitle: Home #display on navigation menu.
  yoursitetitle: Stephanie Hamilton
  gravatar: # Email MD5 hash
  description: "This is the personal website of Stephanie Hamilton, graduate student at the University of Michigan" # used by search engines
  visiblewords: 100
  # Header and footer text
  header_text: >
     "Life need not be easy, provided only that it is not empty." <br>~ Lise Meitner

  header_text_feature_image: img/northern_lights.jpeg
  place_holder_image: img/calm_ripples.jpeg
  footer_text: >
   <a href="www.stephaniejhamilton.com">Stephanie Hamilton</a>

  # Icons
  rss: false
  email_address: "sjhamilton820@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: "sjhamilton820"
  dribbble:
  facebook:
  flickr:
  github: "sjhamil"
  weibo:
  google_plus:
  instagram: "sjhamilton820"
  linkedin: "https://www.linkedin.com/in/stephanie-j-hamilton/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "StephHamy820"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-97843872-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: stephaniejhamilton
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
enforce_ssl: "www.stephaniejhamilton.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/

# Navigation
tag_page: '/tags/'

# Posted in ... with ...
sechby:
  category:   #in
  tag:   #with

# BUILD SETTINGS
include: ["_pages"]
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate
  - jekyll-archives
