# Site settings
title: Stephanie Hamilton
subtitle: " | Astronomy + SciComm"
email: sjhamilton820@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

# Blog settings
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

disqus_shortname: stephaniejhamilton

# Social settings
500px: 
facebook: 
github: sjhamil
gitlab:
instagram: spacescisteph
linkedin: stephanie-j-hamilton
pinterest: 
slack: 
twitter: SpaceSciSteph
youtube: UCEJjhcr29XU0-g053UPL1Yw
orcid: 0000-0002-6126-8487


# Build settings
include: ["_pages"]
markdown: kramdown

plugins_dir: ./_plugins/
plugins:
  - jekyll-archives
  - jekyll-paginate
