# Site settings
title: Stephanie Hamilton
subtitle: " | Astronomy + SciComm"
email: sjhamilton820@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stephanie Hamilton, PhD (she/her) is a planetary scientist and
  science communicator with experience in research, science writing,
  oral presentations, and science communication training.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

# permalink: pretty
permalink: /blog/:year/:month/:day/:title/

# Blog settings
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

disqus_shortname: stephaniejhamilton

# Social settings
500px: 
facebook: 
github: sjhamil
gitlab:
instagram: spacescisteph
linkedin: stephanie-j-hamilton
pinterest: 
slack: 
twitter: SpaceSciSteph
youtube: UCEJjhcr29XU0-g053UPL1Yw
orcid: 0000-0002-6126-8487


# Build settings
include: ["_pages"]
markdown: kramdown

plugins_dir: ./_plugins/
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
